### PR TITLE
Added qbshopsconfig.lua

### PR DESCRIPTION
**Pull request by CptNoHand**
to help someone who wishes to add them to their qb-shops.

### CODE REVIEW

**Comment by realSixGrams** [comment]
I've just done this, and I appreciate you letting me know as I knew I was missing something!

**Comment by realSixGrams** [comment]
By chance, would you know a easier way for me to edit the files in my Repo? As, I am a little new to this, so I am updating these in a fashion that is a pain in the ass, whilst feeling like there is a better way.

**Comment by CptNoHand** [comment]
You also could've merged this and it would have added my file to your repo for the shops config.You can open your repo with Github Desktop and there it will create a copy on your pc and you can edit everything there, just click commit and upload it to github, then it's updated and ready to go. If you add a file into that file path it also shows on the github desktop page and you can upload that aswell. Makes everything super easy.Am 18.12.21, 21:09 schrieb realSixGrams ***@***.***>:

   
  By chance, would you know a easier way for me to edit the files in my Repo? As, I am a little new to this, so I am updating these in a fashion that is a pain in the ass, whilst feeling like there is a better way.

**Comment by CptNoHand** [comment]
Like with this pr request. I did the work of adding that file for you and you could've decided to merge it and it would've updated your repo with my extra file. Am 18.12.21, 21:02 schrieb realSixGrams ***@***.***>:

   
  I've just done this, and I appreciate you letting me know as I knew I was missing something!

**Pull request closed without merging**
